name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{  github.ref != 'refs/heads/main' }}

env:
  COVERAGE: true
  RAILS_ENV: test
  NODE_ENV: test
  DATABASE_URL_TEST: postgres://postgres:postgres@localhost:5432/Forem_test
  DATABASE_NAME_TEST: Forem_test
  KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
  POSTGRES_PASSWORD: postgres

jobs:
  bundle_install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

  yarn_install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Look up if node_module cache exist
        id: cache
        uses: actions/cache/restore@v3
        with:
          lookup-only: true
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
        if: steps.cache.outputs.cache-hit != 'true'
      - uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
        if: steps.cache.outputs.cache-hit != 'true'

  precompile_assets:
    runs-on: ubuntu-latest
    env:
      E2E: true

    steps:
      - uses: actions/checkout@v3
      - name: Look up if compiled assets exist
        uses: actions/cache@v3
        id: precompiled-asset
        with:
          fail-on-cache-miss: false
          path: |
            public/assets
            public/packs-test
            tmp/cache/webpacker
          key: ${{ runner.os }}-compiled-assets-v2-${{ hashFiles('app/assets/**', 'app/javascript/**', 'config/webpack/**', 'config/webpacker.yml', '**/package.json', '**/yarn.lock', '**/babel.config.js') }}
          restore-keys: ${{ runner.os }}-compiled-assets-v2-
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        if: steps.precompiled-asset.outputs.cache-hit != 'true'
      - name: Cache node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
        if: steps.precompiled-asset.outputs.cache-hit != 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
        if: steps.precompiled-asset.outputs.cache-hit != 'true'
      - run: yarn install --immutable
        if: steps.precompiled-asset.outputs.cache-hit != 'true'
      - run: bundle exec rails assets:precompile
        if: steps.precompiled-asset.outputs.cache-hit != 'true'

  
  storybook:
    runs-on: ubuntu-latest
    needs: [yarn_install]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - name: Restore node_modules
        uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn build-storyboo


  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    concurrency: ${{ matrix.environment }}
    environment: ${{ matrix.environment }}

    strategy:
      matrix:
        environment: [ production, staging ]

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
      - uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY_RUBY }}
        if: matrix.environment == 'production'
      - uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY_JAVASCRIPT }}
        if: matrix.environment == 'production'
